-- 코드를 작성해주세요
SELECT f.ITEM_ID, f.ITEM_NAME, f.RARITY
FROM ITEM_INFO AS f
WHERE f.ITEM_ID NOT IN (SELECT f.ITEM_ID
FROM ITEM_INFO AS f
JOIN ITEM_TREE AS g
ON f.ITEM_ID = g.PARENT_ITEM_ID)
ORDER BY f.ITEM_ID DESC