-- 코드를 작성해주세요
WITH a AS (SELECT h.PARENT_ID, COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA AS h
WHERE h.PARENT_ID IS NOT null
GROUP BY h.PARENT_ID)

SELECT h.ID, ifnull(a.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS h
LEFT OUTER JOIN a
ON h.ID = a.PARENT_ID;