-- 코드를 입력하세요
SELECT g.USER_ID, g.NICKNAME, SUM(f.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS f
JOIN USED_GOODS_USER AS g
ON f.WRITER_ID = g.USER_ID
WHERE f.STATUS = 'DONE'
GROUP BY f.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES